_target_: src.models.cl_module.ContrastiveLearningModule

compile: True
initial_temperature: .07
clusters_list: [5,10,15]
optimizer: &adam_optimizer
  _target_: torch.optim.Adam
  _partial_: true
  lr: .0001
  weight_decay: 0.0

net:
  _target_: src.models.components.ae.AE
  input_channels: 3
  input_dim: ${eval:'${data.im_size[0]}'}
  latent_dim: 20

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 3
