# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: mnist
  - model: ae
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: sss_segmentation


task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
#ckpt_path: /lustre/cniel/onr/logs/train/runs/2024-06-03_16-26-09/checkpoints/last.ckpt
ckpt_path:  /lustre/cniel/onr/logs/train/runs/2025-03-14_04-13-52/checkpoints/epoch_128.ckpt